### ISSUE TITLE
Checklist showing implemented elements of csaf document

### ISSUE THREAD

**Issue by ThomasJunk** [csaf-poc/csaf_webview#17]
## Document

- [x] acknowledgments
- [x] aggregate_severity
- [x] category
- [x] csaf_version
- [x] distribution
- [x] lang
- [x] notes
- [x] publisher
- [x] references
- [x] source_lang
- [x] title
- [x] tracking 
    - [x] aliases
    - [x] current_release_date
    - [x] generator
    - [x] id
    - [x] initial release_date
    - [x] revision history
    - [x] status
    - [x] version

## Product Tree

- [x] branches
- [x] full_product_names
- [x] product_groups
- [x] relationships

## Vulnerabilities

- [x] acknowledgements
- [x] cve
- [x] cwe
- [x] discovery date
- [x] flags
- [x] ids
- [x] involvements
- [x] notes
- [x] product_status
- [x] references
- [x] release_date
- [x] remediations
- [x] scores
- [x] threats
- [x] title

**Comment by ThomasJunk** [comment]
This was more of a personal checklist but I think it is good for general documentation purposes so I include it here.

**Comment by ThomasJunk** [comment]
Closing here
